## Introduction to `numpy`

Let's start by running the following cell.

In [ ]:
import numpy as np

As introduced in the pre-recorded lectures, `numpy` is a fast numerical computation module for Python. The basic tools that `numpy` offers are the *array* data structure and *vectorized* implementations of functions on arrays. In this worksheet, we will assume familiarity with the content of the `numpy` lectures.

To recap, a `numpy` array is implemented as a C array: it is a contiguous block of memory that stores data all of the same type. This is in contrast with native Python lists, which are implemented as C arrays that store pointers to their contents, which can be scattered throughout memory. Eliminating this non-locality and the overhead cost of dynamic type checking (which lists must perform even if all their elements are of the same type) leads to a significant edge in speed for `numpy` arrays. This is why we use them.

In [ ]:
a = np.random.rand(1000)
b = np.random.rand(1000)

a_list = list(a)
b_list = list(b)

In the next cell, write a list comprehension that makes a new list `c_list` whose elements are products of corresponding elements of `a_list` and `b_list`. (Leave the `%%timeit` decorator in the cell; this will let you measure the speed of execution.)

In [ ]:
%%timeit
# write your code here

Make a new array `c` filled with 1000 zeros. Write a `for` loop that iterates over the elements of arrays `a` and `b` and assigns their product to the corresponding entry of `c`. (The results should convince you that you should always avoid doing this.)

In [ ]:
%%timeit
# write your code here

Now make `c` again, this time by multiplying the corresponding pairs of elements of `a` and `b` using the `numpy` vectorized multiplication.

In [ ]:
%%timeit
# write your code here

What do you observe about the performance of each operation? (1 ms = 1000 µs, 1 µs = 1000 ns.)

*write your answer here*

### §1. Building arrays

In the following exercises, build the indicated arrays using `numpy` functions. Don't use lists or loops. Try not to store anything into variables -- you don't need to yet. You can do these in any order.

```
array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])
```

In [ ]:
# this is an example
np.arange(5, 25)

```
array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])
```

In [ ]:
# write your code here

```
array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])
```

```
array([1., 1., 1., 1., 1.])
```

```
array([[1., 1.],
       [1., 1.],
       [1., 1.]])
```

```
array([[7., 7.],
       [7., 7.],
       [7., 7.]])
```

```
array([ 1,  4,  7, 10, 13])
```

```
array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])
```

```
array([ 0.,  2.,  4.,  6.,  8., 10.])
```

```
array([20., 15., 10.,  5.,  0.])
```

```
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])
```

```
array([False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])
```

In [ ]:
# there are 20 entires

```
array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])
```

```
array([False, False, False, False, False, False, False, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])
```

From this point on it might help to store the arrays to variables. (I suggest just reusing the same variable name; these problems shouldn't depend on each other.)

```
array([ 0,  1,  2,  0,  4,  5,  0,  7,  8,  0, 10, 11,  0, 13, 14,  0, 16,
       17,  0, 19])
```

```
array([ 0,  1,  0,  3,  0,  0,  0,  7,  0,  9,  0, 11,  0, 13,  0,  0,  0,
       17,  0, 19])
```

```
array([[0, 1, 2, 3],
       [4, 5, 6, 0],
       [0, 0, 0, 0]])
```

```
array([[ 0,  1,  2, 13],
       [14, 15, 16, 17],
       [18, 19, 10, 11]])
```

```
array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])
```

In [ ]:
# hint: use the // operator -- test it to see what it does

```
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])
```

In [ ]:
# hint: build two arrays

### §2. Slicing multidimensional arrays

Run the next cell first.

In [ ]:
A = np.arange(28).reshape(4, 7)
A

Obtain the following arrays by slicing `A`.

```
array([ 7,  8,  9, 10, 11, 12, 13])
```

```
array([ 4, 11, 18, 25])
```

```
array([[ 9, 10, 11],
       [16, 17, 18],
       [23, 24, 25]])
```

```
array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11],
       [15, 16, 17, 18],
       [22, 23, 24, 25]])
```

```
array([[ 0,  2,  4,  6],
       [ 7,  9, 11, 13],
       [14, 16, 18, 20],
       [21, 23, 25, 27]])
```

```
array([[ 0,  3,  5,  6],
       [ 7, 10, 12, 13]])
```

### §3. Bonus

Run the following cell and observe the output.

In [ ]:
A = np.arange(20).reshape(4,5)

print(A, A.sum(), A.sum(0), A.sum(1), sep='\n\n')

In [ ]:
v = np.arange(1, 6)
v

On one line, using the above functions, write an expression for the matrix product `Av`, considering `v` as a column vector.

Explain why your answer works.

*write your answer here*